# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-05 03:38
from __future__ import unicode_literals

import ckeditor.fields
import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='illic', max_length=140)),
                ('social_description', models.CharField(default='Social description', max_length=140)),
                ('who', ckeditor.fields.RichTextField(verbose_name='¿Quiénes somos?')),
                ('when', ckeditor.fields.RichTextField(verbose_name='¿Cuándo acudir a Terapia')),
                ('phone', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=140)),
                ('footer_message', models.CharField(max_length=140)),
            ],
            options={
                'verbose_name': 'Textos del sitio',
                'verbose_name_plural': 'Textos del sitio',
            },
        ),
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('title', models.CharField(default='Terapia', max_length=140)),
                ('slug', models.CharField(editable=False, max_length=200)),
                ('image', models.FileField(upload_to=cms.models.upload_to_therapy)),
            ],
            options={
                'verbose_name': 'Terapia',
                'verbose_name_plural': 'Terapias',
                'ordering': ['order'],
            },
        ),
    ]
