# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-05 03:45
from __future__ import unicode_literals

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='facebook',
            field=models.URLField(default='https://www.facebook.com/', max_length=140),
        ),
        migrations.AddField(
            model_name='site',
            name='preview_image',
            field=models.ImageField(default=1, upload_to=cms.models.upload_to_therapy),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='twitter',
            field=models.URLField(default='https://twitter.com/', max_length=140),
        ),
    ]
