# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-05 03:51
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20170605_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapy',
            name='small_text',
            field=models.CharField(default='Terapia', max_length=140),
        ),
        migrations.AddField(
            model_name='therapy',
            name='text',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
