# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 16:26
from __future__ import unicode_literals

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20170605_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('title', models.CharField(default='Terapia', max_length=140, verbose_name='Nombre')),
                ('slug', models.CharField(editable=False, max_length=200)),
                ('phone', models.CharField(max_length=140)),
                ('address', models.CharField(max_length=250)),
                ('google_maps', models.URLField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='site',
            name='preview_image',
            field=models.ImageField(upload_to=cms.models.upload_to),
        ),
    ]
