# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20170605_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapist',
            options={'ordering': ['order'], 'verbose_name': 'Terapeuta', 'verbose_name_plural': 'Terapeutas'},
        ),
        migrations.AlterField(
            model_name='therapist',
            name='title',
            field=models.CharField(default='Terapeuta', max_length=140, verbose_name='Nombre'),
        ),
    ]
