# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 19:31
from __future__ import unicode_literals

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20170605_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='who_image',
            field=models.ImageField(default=1, upload_to=cms.models.upload_to),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='title',
            field=models.CharField(default='Illic', max_length=140),
        ),
    ]
