# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 20:09
from __future__ import unicode_literals

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20170609_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='when_image',
            field=models.ImageField(default=1, upload_to=cms.models.upload_to),
            preserve_default=False,
        ),
    ]
