# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 20:33
from __future__ import unicode_literals

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_site_when_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapy',
            name='large_image',
            field=models.FileField(default=1, upload_to=cms.models.upload_to),
            preserve_default=False,
        ),
    ]
