# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 10:13
from __future__ import unicode_literals

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_therapy_large_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='image',
            field=models.ImageField(default=1, upload_to=cms.models.upload_to_therapist),
            preserve_default=False,
        ),
    ]
