# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170617_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
